import {supabase} from '../config/supabase';
import {Loan, LoanInput} from '../types/loan';

type LoanRow = {id: string; uid: string; direction: Loan['direction']; party_name: string; principal: number | string; interest_rate: number | string | null; started_at: string; due_at: string | null; status: Loan['status']; note: string | null; created_at: string | null; updated_at: string | null};
const requireUid = async () => { const {data: {user}} = await supabase.auth.getUser(); if (!user) throw new Error('You must be logged in to manage loans.'); return user.id; };
const fromRow = (row: LoanRow): Loan => ({id: row.id, uid: row.uid, direction: row.direction, partyName: row.party_name, principal: Number(row.principal), ...(row.interest_rate == null ? {} : {interestRate: Number(row.interest_rate)}), startedAt: new Date(row.started_at), ...(row.due_at ? {dueAt: new Date(row.due_at)} : {}), status: row.status, ...(row.note ? {note: row.note} : {}), ...(row.created_at ? {createdAt: new Date(row.created_at)} : {}), ...(row.updated_at ? {updatedAt: new Date(row.updated_at)} : {})});
const toRow = (input: LoanInput) => ({direction: input.direction, party_name: input.partyName, principal: input.principal, interest_rate: input.interestRate ?? null, started_at: input.startedAt.toISOString(), due_at: input.dueAt?.toISOString() ?? null, status: input.status, note: input.note ?? null});
export const listLoans = async () => { const uid = await requireUid(); const {data, error} = await supabase.from('loans').select('*').eq('uid', uid).order('started_at', {ascending: false}); if (error) throw error; return (data ?? []).map(row => fromRow(row as LoanRow)); };
export const addLoan = async (input: LoanInput) => { const uid = await requireUid(); const {data, error} = await supabase.from('loans').insert({uid, ...toRow(input)}).select().single(); if (error) throw error; return fromRow(data as LoanRow); };
export const updateLoan = async (id: string, input: Partial<LoanInput>) => { await requireUid(); const update: Record<string, unknown> = {...input}; if (input.partyName !== undefined) { update.party_name = input.partyName; delete update.partyName; } if (input.interestRate !== undefined) { update.interest_rate = input.interestRate; delete update.interestRate; } if (input.startedAt) { update.started_at = input.startedAt.toISOString(); delete update.startedAt; } if (input.dueAt !== undefined) { update.due_at = input.dueAt?.toISOString() ?? null; delete update.dueAt; } const {error} = await supabase.from('loans').update(update).eq('id', id); if (error) throw error; };
export const deleteLoan = async (id: string) => { await requireUid(); const {error} = await supabase.from('loans').delete().eq('id', id); if (error) throw error; };
export const listenLoans = (callback: (items: Loan[]) => void, onError?: (error: Error) => void) => { let active = true; const load = async () => { try { const items = await listLoans(); if (active) callback(items); } catch (error) { if (active) onError?.(error instanceof Error ? error : new Error(String(error))); } }; load(); const channel = supabase.channel('loans').on('postgres_changes', {event: '*', schema: 'public', table: 'loans'}, load).subscribe(); return () => { active = false; supabase.removeChannel(channel); }; };
