import {supabase} from '../config/supabase';
import {Loan, LoanInput, LoanMovement} from '../types/loan';

type LoanRow = {id: string; uid: string; direction: Loan['direction']; party_name: string; principal: number | string; interest_rate: number | string | null; started_at: string; due_at: string | null; status: Loan['status']; note: string | null; created_at: string | null; updated_at: string | null};
type LoanMovementRow = {id: string; uid: string; loan_id: string; kind: LoanMovement['kind']; amount: number | string; date: string; note: string | null; created_at: string | null};
const requireUid = async () => { const {data: {user}} = await supabase.auth.getUser(); if (!user) throw new Error('You must be logged in to manage loans.'); return user.id; };
const fromRow = (row: LoanRow): Loan => ({id: row.id, uid: row.uid, direction: row.direction, partyName: row.party_name, principal: Number(row.principal), ...(row.interest_rate == null ? {} : {interestRate: Number(row.interest_rate)}), startedAt: new Date(row.started_at), ...(row.due_at ? {dueAt: new Date(row.due_at)} : {}), status: row.status, ...(row.note ? {note: row.note} : {}), ...(row.created_at ? {createdAt: new Date(row.created_at)} : {}), ...(row.updated_at ? {updatedAt: new Date(row.updated_at)} : {})});
const toRow = (input: LoanInput) => ({direction: input.direction, party_name: input.partyName, principal: input.principal, interest_rate: input.interestRate ?? null, started_at: input.startedAt.toISOString(), due_at: input.dueAt?.toISOString() ?? null, status: input.status, note: input.note ?? null});
const fromMovementRow = (row: LoanMovementRow): LoanMovement => ({id: row.id, uid: row.uid, loanId: row.loan_id, kind: row.kind, amount: Number(row.amount), date: new Date(row.date), ...(row.note ? {note: row.note} : {}), ...(row.created_at ? {createdAt: new Date(row.created_at)} : {})});
export const listLoanMovements = async (loanId?: string) => { const uid = await requireUid(); let query = supabase.from('loan_movements').select('*').eq('uid', uid); if (loanId) query = query.eq('loan_id', loanId); const {data, error} = await query.order('date', {ascending: false}); if (error) throw error; return (data ?? []).map(row => fromMovementRow(row as LoanMovementRow)); };
export const listLoans = async () => { const uid = await requireUid(); const {data, error} = await supabase.from('loans').select('*').eq('uid', uid).order('started_at', {ascending: false}); if (error) throw error; const loans = (data ?? []).map(row => fromRow(row as LoanRow)); const {data: movementData, error: movementError} = await supabase.from('loan_movements').select('*').eq('uid', uid); if (movementError) throw movementError; const movements = (movementData ?? []).map(row => fromMovementRow(row as LoanMovementRow)); return loans.map(loan => ({...loan, outstanding: Math.max(0, loan.principal - movements.filter(movement => movement.loanId === loan.id && movement.kind === 'repayment').reduce((sum, movement) => sum + movement.amount, 0))})); };
export const addLoan = async (input: LoanInput) => { const uid = await requireUid(); const {data, error} = await supabase.from('loans').insert({uid, ...toRow(input)}).select().single(); if (error) throw error; const loan = fromRow(data as LoanRow); const {error: movementError} = await supabase.from('loan_movements').insert({uid, loan_id: loan.id, kind: 'disbursement', amount: loan.principal, date: loan.startedAt.toISOString(), note: null}); if (movementError) throw movementError; return loan; };
export const addLoanRepayment = async (loanId: string, amount: number, date: Date, note?: string) => { const uid = await requireUid(); const {error} = await supabase.from('loan_movements').insert({uid, loan_id: loanId, kind: 'repayment', amount, date: date.toISOString(), note: note ?? null}); if (error) throw error; };
export const updateLoan = async (id: string, input: Partial<LoanInput>) => { await requireUid(); const update: Record<string, unknown> = {...input}; if (input.partyName !== undefined) { update.party_name = input.partyName; delete update.partyName; } if (input.interestRate !== undefined) { update.interest_rate = input.interestRate; delete update.interestRate; } if (input.startedAt) { update.started_at = input.startedAt.toISOString(); delete update.startedAt; } if (input.dueAt !== undefined) { update.due_at = input.dueAt?.toISOString() ?? null; delete update.dueAt; } const {error} = await supabase.from('loans').update(update).eq('id', id); if (error) throw error; };
export const deleteLoan = async (id: string) => { await requireUid(); const {error} = await supabase.from('loans').delete().eq('id', id); if (error) throw error; };
export const listenLoans = (callback: (items: Loan[]) => void, onError?: (error: Error) => void) => { let active = true; const load = async () => { try { const items = await listLoans(); if (active) callback(items); } catch (error) { if (active) onError?.(error instanceof Error ? error : new Error(String(error))); } }; load(); const channel = supabase.channel('loans').on('postgres_changes', {event: '*', schema: 'public', table: 'loans'}, load).subscribe(); return () => { active = false; supabase.removeChannel(channel); }; };
