import React, {useLayoutEffect, useState} from 'react';
import {Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput} from 'react-native';
import {Save, Trash2} from 'lucide-react-native';
import {NativeStackScreenProps} from '@react-navigation/native-stack';
import {FDStackParamList} from '../navigation/types';
import {addFixedDeposit, deleteFixedDeposit, updateFixedDeposit} from '../services/fdService';
import {FixedDepositStatus} from '../types/fixedDeposit';
import {Colors, controlHeight, radius, spacing} from '../constants/theme';
import {useTheme} from '../context/ThemeContext';
import AmountInput from '../components/AmountInput';
import DateField from '../components/DateField';

type Props = NativeStackScreenProps<FDStackParamList, 'AddFD'>;
export default function AddFixedDepositScreen({navigation, route}: Props) {
  const {colors} = useTheme(); const styles = createStyles(colors); const existing = route.params?.deposit; const editing = Boolean(existing);
  const [name, setName] = useState(existing?.name ?? ''); const [principal, setPrincipal] = useState(existing?.principal.toString() ?? ''); const [rate, setRate] = useState(existing?.interestRate?.toString() ?? ''); const [maturityAmount, setMaturityAmount] = useState(existing?.maturityAmount?.toString() ?? ''); const [startedAt, setStartedAt] = useState(existing?.startedAt ?? new Date()); const [maturityAt, setMaturityAt] = useState(existing?.maturityAt ?? new Date()); const [note, setNote] = useState(existing?.note ?? ''); const [saving, setSaving] = useState(false);
  useLayoutEffect(() => { navigation.setOptions({title: editing ? 'Edit fixed deposit' : 'Add fixed deposit'}); }, [editing, navigation]);
  const save = async () => { const amount = Number(principal); if (!name.trim() || !amount || amount <= 0) { Alert.alert('Add deposit details', 'Enter a name and principal amount.'); return; } if (maturityAt < startedAt) { Alert.alert('Check dates', 'Maturity date must be after the start date.'); return; } setSaving(true); try { const input = {name: name.trim(), principal: amount, interestRate: rate ? Number(rate) : undefined, maturityAmount: maturityAmount ? Number(maturityAmount) : undefined, startedAt, maturityAt, status: (existing?.status ?? 'active') as FixedDepositStatus, ...(note.trim() ? {note: note.trim()} : {})}; if (existing) await updateFixedDeposit(existing.id, input); else await addFixedDeposit(input); navigation.goBack(); } catch { Alert.alert('Could not save fixed deposit', 'Please check your connection and try again.'); } finally { setSaving(false); } };
  const remove = () => { if (!existing) return; Alert.alert('Delete fixed deposit?', 'This cannot be undone.', [{text: 'Cancel', style: 'cancel'}, {text: 'Delete', style: 'destructive', onPress: async () => {await deleteFixedDeposit(existing.id); navigation.goBack();}}]); };
  return <KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.label}>Name</Text><TextInput value={name} onChangeText={setName} placeholder="SBI FD" placeholderTextColor={colors.inkMuted} style={styles.input} /><Text style={styles.label}>Principal</Text><AmountInput value={principal} onChangeText={setPrincipal} /><Text style={styles.label}>Start date</Text><DateField value={startedAt} onChange={setStartedAt} /><Text style={styles.label}>Maturity date</Text><DateField value={maturityAt} onChange={setMaturityAt} /><Text style={styles.label}>Interest rate (%) <Text style={styles.optional}>(optional)</Text></Text><TextInput value={rate} onChangeText={setRate} keyboardType="decimal-pad" placeholder="0" placeholderTextColor={colors.inkMuted} style={styles.input} /><Text style={styles.label}>Maturity amount <Text style={styles.optional}>(optional)</Text></Text><AmountInput value={maturityAmount} onChangeText={setMaturityAmount} /><Text style={styles.label}>Note <Text style={styles.optional}>(optional)</Text></Text><TextInput value={note} onChangeText={setNote} placeholder="Optional note" placeholderTextColor={colors.inkMuted} style={[styles.input, styles.note]} multiline /><Pressable onPress={save} disabled={saving} style={({pressed}) => [styles.save, pressed && styles.pressed, saving && styles.disabled]}><Text style={styles.saveText}>{saving ? 'Saving…' : editing ? 'Save changes' : 'Save deposit'}</Text>{!saving ? <Save size={17} color={colors.white} strokeWidth={2.25} /> : null}</Pressable>{editing ? <Pressable onPress={remove} style={styles.delete}><Trash2 size={16} color={colors.expense} /><Text style={styles.deleteText}>Delete deposit</Text></Pressable> : null}</ScrollView></KeyboardAvoidingView>;
}

const createStyles = (colors: Colors) => StyleSheet.create({flex: {flex: 1, backgroundColor: colors.canvas}, content: {padding: spacing.lg, paddingBottom: spacing.xl * 3}, label: {color: colors.ink, fontSize: 12, fontWeight: '800', marginTop: spacing.lg, marginBottom: spacing.sm}, optional: {color: colors.inkMuted, fontWeight: '500'}, input: {height: controlHeight.md, backgroundColor: colors.surface, borderRadius: radius.md, color: colors.ink, fontSize: 14, paddingHorizontal: spacing.md}, note: {height: 80, paddingVertical: spacing.sm, textAlignVertical: 'top'}, save: {minHeight: controlHeight.lg, marginTop: spacing.xl, borderRadius: radius.md, backgroundColor: colors.primary, flexDirection: 'row', gap: spacing.xs, alignItems: 'center', justifyContent: 'center'}, saveText: {color: colors.white, fontSize: 14, fontWeight: '800'}, pressed: {opacity: 0.8}, disabled: {opacity: 0.65}, delete: {flexDirection: 'row', gap: spacing.xs, alignItems: 'center', justifyContent: 'center', padding: spacing.md}, deleteText: {color: colors.expense, fontWeight: '700', fontSize: 12}});
