import React, {useLayoutEffect, useState} from 'react';
import {Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View} from 'react-native';
import {Save, Trash2} from 'lucide-react-native';
import {NativeStackScreenProps} from '@react-navigation/native-stack';
import {GoldStackParamList} from '../navigation/types';
import {addGold, deleteGold, updateGold} from '../services/goldService';
import {GoldStatus} from '../types/gold';
import {Colors, controlHeight, radius, spacing} from '../constants/theme';
import {useTheme} from '../context/ThemeContext';
import AmountInput from '../components/AmountInput';
import DateField from '../components/DateField';

type Props = NativeStackScreenProps<GoldStackParamList, 'AddGold'>;
export default function AddGoldScreen({navigation, route}: Props) {
  const {colors} = useTheme(); const styles = createStyles(colors); const existing = route.params?.holding; const editing = Boolean(existing);
  const [name, setName] = useState(existing?.name ?? ''); const [amount, setAmount] = useState(existing?.purchaseAmount.toString() ?? ''); const [currentValue, setCurrentValue] = useState(existing?.currentValue?.toString() ?? ''); const [weight, setWeight] = useState(existing?.weight?.toString() ?? ''); const [purity, setPurity] = useState(existing?.purity?.toString() ?? ''); const [date, setDate] = useState(existing?.purchasedAt ?? new Date()); const [note, setNote] = useState(existing?.note ?? ''); const [saving, setSaving] = useState(false);
  useLayoutEffect(() => { navigation.setOptions({title: editing ? 'Edit gold holding' : 'Add gold holding'}); }, [editing, navigation]);
  const save = async () => { const numericAmount = Number(amount); if (!name.trim() || !numericAmount || numericAmount <= 0) { Alert.alert('Add holding details', 'Enter a name and purchase amount.'); return; } setSaving(true); try { const input = {name: name.trim(), purchaseAmount: numericAmount, currentValue: currentValue ? Number(currentValue) : undefined, weight: weight ? Number(weight) : undefined, purity: purity ? Number(purity) : undefined, purchasedAt: date, status: (existing?.status ?? 'active') as GoldStatus, soldAt: existing?.soldAt, ...(note.trim() ? {note: note.trim()} : {})}; if (existing) await updateGold(existing.id, input); else await addGold(input); navigation.goBack(); } catch { Alert.alert('Could not save gold holding', 'Please check your connection and try again.'); } finally { setSaving(false); } };
  const remove = () => { if (!existing) return; Alert.alert('Delete gold holding?', 'This cannot be undone.', [{text: 'Cancel', style: 'cancel'}, {text: 'Delete', style: 'destructive', onPress: async () => {await deleteGold(existing.id); navigation.goBack();}}]); };
  return <KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.label}>Name</Text><TextInput value={name} onChangeText={setName} placeholder="Gold coins" placeholderTextColor={colors.inkMuted} style={styles.input} /><Text style={styles.label}>Purchase amount</Text><AmountInput value={amount} onChangeText={setAmount} /><Text style={styles.label}>Current value <Text style={styles.optional}>(optional)</Text></Text><AmountInput value={currentValue} onChangeText={setCurrentValue} /><Text style={styles.label}>Purchase date</Text><DateField value={date} onChange={setDate} /><View style={styles.row}><View style={styles.half}><Text style={styles.label}>Weight (g)</Text><TextInput value={weight} onChangeText={setWeight} keyboardType="decimal-pad" placeholder="0" placeholderTextColor={colors.inkMuted} style={styles.input} /></View><View style={styles.half}><Text style={styles.label}>Purity (%)</Text><TextInput value={purity} onChangeText={setPurity} keyboardType="decimal-pad" placeholder="0" placeholderTextColor={colors.inkMuted} style={styles.input} /></View></View><Text style={styles.label}>Note <Text style={styles.optional}>(optional)</Text></Text><TextInput value={note} onChangeText={setNote} placeholder="Optional note" placeholderTextColor={colors.inkMuted} style={[styles.input, styles.note]} multiline /><Pressable onPress={save} disabled={saving} style={({pressed}) => [styles.save, pressed && styles.pressed, saving && styles.disabled]}><Text style={styles.saveText}>{saving ? 'Saving…' : editing ? 'Save changes' : 'Save holding'}</Text>{!saving ? <Save size={17} color={colors.white} strokeWidth={2.25} /> : null}</Pressable>{editing ? <Pressable onPress={remove} style={styles.delete}><Trash2 size={16} color={colors.expense} /><Text style={styles.deleteText}>Delete holding</Text></Pressable> : null}</ScrollView></KeyboardAvoidingView>;
}

const createStyles = (colors: Colors) => StyleSheet.create({flex: {flex: 1, backgroundColor: colors.canvas}, content: {padding: spacing.lg, paddingBottom: spacing.xl * 3}, label: {color: colors.ink, fontSize: 12, fontWeight: '800', marginTop: spacing.lg, marginBottom: spacing.sm}, optional: {color: colors.inkMuted, fontWeight: '500'}, input: {height: controlHeight.md, backgroundColor: colors.surface, borderRadius: radius.md, color: colors.ink, fontSize: 14, paddingHorizontal: spacing.md}, note: {height: 80, paddingVertical: spacing.sm, textAlignVertical: 'top'}, row: {flexDirection: 'row', gap: spacing.sm}, half: {flex: 1}, save: {minHeight: controlHeight.lg, marginTop: spacing.xl, borderRadius: radius.md, backgroundColor: colors.primary, flexDirection: 'row', gap: spacing.xs, alignItems: 'center', justifyContent: 'center'}, saveText: {color: colors.white, fontSize: 14, fontWeight: '800'}, pressed: {opacity: 0.8}, disabled: {opacity: 0.65}, delete: {flexDirection: 'row', gap: spacing.xs, alignItems: 'center', justifyContent: 'center', padding: spacing.md}, deleteText: {color: colors.expense, fontWeight: '700', fontSize: 12}});
