import React, {useLayoutEffect, useState} from 'react';
import {Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View} from 'react-native';
import {Save, Trash2} from 'lucide-react-native';
import {NativeStackScreenProps} from '@react-navigation/native-stack';
import {LoansStackParamList} from '../navigation/types';
import {addLoan, addLoanRepayment, deleteLoan, updateLoan} from '../services/loanService';
import {LoanDirection, LoanStatus} from '../types/loan';
import {Colors, controlHeight, radius, spacing} from '../constants/theme';
import {useTheme} from '../context/ThemeContext';
import AmountInput from '../components/AmountInput';
import DateField from '../components/DateField';

type Props = NativeStackScreenProps<LoansStackParamList, 'AddLoan'>;
export default function AddLoanScreen({navigation, route}: Props) {
  const {colors} = useTheme(); const styles = createStyles(colors); const existing = route.params?.loan; const editing = Boolean(existing);
  const [direction, setDirection] = useState<LoanDirection>(existing?.direction ?? 'given'); const [partyName, setPartyName] = useState(existing?.partyName ?? ''); const [principal, setPrincipal] = useState(existing?.principal.toString() ?? ''); const [rate, setRate] = useState(existing?.interestRate?.toString() ?? ''); const [startedAt, setStartedAt] = useState(existing?.startedAt ?? new Date()); const [dueAt, setDueAt] = useState(existing?.dueAt ?? new Date()); const [note, setNote] = useState(existing?.note ?? ''); const [repayment, setRepayment] = useState(''); const [saving, setSaving] = useState(false);
  useLayoutEffect(() => { navigation.setOptions({title: editing ? 'Edit loan' : 'Add loan'}); }, [editing, navigation]);
  const save = async () => { const amount = Number(principal); if (!partyName.trim() || !amount || amount <= 0) { Alert.alert('Add loan details', 'Enter a party name and principal amount.'); return; } setSaving(true); try { const input = {direction, partyName: partyName.trim(), principal: amount, interestRate: rate ? Number(rate) : undefined, startedAt, dueAt, status: (existing?.status ?? 'active') as LoanStatus, ...(note.trim() ? {note: note.trim()} : {})}; if (existing) await updateLoan(existing.id, input); else await addLoan(input); navigation.goBack(); } catch { Alert.alert('Could not save loan', 'Please check your connection and try again.'); } finally { setSaving(false); } };
  const remove = () => { if (!existing) return; Alert.alert('Delete loan?', 'This cannot be undone.', [{text: 'Cancel', style: 'cancel'}, {text: 'Delete', style: 'destructive', onPress: async () => {await deleteLoan(existing.id); navigation.goBack();}}]); };
  const recordRepayment = async () => { const amount = Number(repayment); if (!existing || !amount || amount <= 0 || amount > (existing.outstanding ?? existing.principal)) { Alert.alert('Check repayment amount', 'Enter an amount up to the outstanding balance.'); return; } setSaving(true); try { await addLoanRepayment(existing.id, amount, new Date()); navigation.goBack(); } catch { Alert.alert('Could not record repayment', 'Please check your connection and try again.'); } finally { setSaving(false); } };
  return <KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.label}>Loan direction</Text><View style={styles.toggle}>{(['given', 'taken'] as LoanDirection[]).map(item => <Pressable key={item} onPress={() => setDirection(item)} style={[styles.option, direction === item && styles.selected]}><Text style={[styles.optionText, direction === item && styles.selectedText]}>{item === 'given' ? 'Loan given' : 'Loan taken'}</Text></Pressable>)}</View><Text style={styles.label}>Party name</Text><TextInput value={partyName} onChangeText={setPartyName} placeholder="Person or organization" placeholderTextColor={colors.inkMuted} style={styles.input} /><Text style={styles.label}>Principal</Text><AmountInput value={principal} onChangeText={setPrincipal} /><Text style={styles.label}>Start date</Text><DateField value={startedAt} onChange={setStartedAt} /><Text style={styles.label}>Due date <Text style={styles.optional}>(optional)</Text></Text><DateField value={dueAt} onChange={setDueAt} /><Text style={styles.label}>Interest rate (%) <Text style={styles.optional}>(optional)</Text></Text><TextInput value={rate} onChangeText={setRate} keyboardType="decimal-pad" placeholder="0" placeholderTextColor={colors.inkMuted} style={styles.input} /><Text style={styles.label}>Note <Text style={styles.optional}>(optional)</Text></Text><TextInput value={note} onChangeText={setNote} placeholder="Optional note" placeholderTextColor={colors.inkMuted} style={[styles.input, styles.note]} multiline />{editing ? <><Text style={styles.label}>Record repayment</Text><AmountInput value={repayment} onChangeText={setRepayment} /><Pressable onPress={recordRepayment} disabled={saving} style={styles.secondary}><Text style={styles.secondaryText}>Add repayment</Text></Pressable></> : null}<Pressable onPress={save} disabled={saving} style={({pressed}) => [styles.save, pressed && styles.pressed, saving && styles.disabled]}><Text style={styles.saveText}>{saving ? 'Saving…' : editing ? 'Save changes' : 'Save loan'}</Text>{!saving ? <Save size={17} color={colors.white} strokeWidth={2.25} /> : null}</Pressable>{editing ? <Pressable onPress={remove} style={styles.delete}><Trash2 size={16} color={colors.expense} /><Text style={styles.deleteText}>Delete loan</Text></Pressable> : null}</ScrollView></KeyboardAvoidingView>;
}

const createStyles = (colors: Colors) => StyleSheet.create({flex: {flex: 1, backgroundColor: colors.canvas}, content: {padding: spacing.lg, paddingBottom: spacing.xl * 3}, label: {color: colors.ink, fontSize: 12, fontWeight: '800', marginTop: spacing.lg, marginBottom: spacing.sm}, optional: {color: colors.inkMuted, fontWeight: '500'}, toggle: {flexDirection: 'row', padding: spacing.xs, backgroundColor: colors.surfaceMuted, borderRadius: radius.md}, option: {flex: 1, minHeight: controlHeight.sm, alignItems: 'center', justifyContent: 'center', borderRadius: radius.sm}, selected: {backgroundColor: colors.surface}, optionText: {color: colors.inkMuted, fontWeight: '700', fontSize: 12}, selectedText: {color: colors.ink}, input: {height: controlHeight.md, backgroundColor: colors.surface, borderRadius: radius.md, color: colors.ink, fontSize: 14, paddingHorizontal: spacing.md}, note: {height: 80, paddingVertical: spacing.sm, textAlignVertical: 'top'}, secondary: {minHeight: controlHeight.md, borderRadius: radius.md, borderWidth: 1, borderColor: colors.primary, alignItems: 'center', justifyContent: 'center'}, secondaryText: {color: colors.primary, fontSize: 13, fontWeight: '800'}, save: {minHeight: controlHeight.lg, marginTop: spacing.xl, borderRadius: radius.md, backgroundColor: colors.primary, flexDirection: 'row', gap: spacing.xs, alignItems: 'center', justifyContent: 'center'}, saveText: {color: colors.white, fontSize: 14, fontWeight: '800'}, pressed: {opacity: 0.8}, disabled: {opacity: 0.65}, delete: {flexDirection: 'row', gap: spacing.xs, alignItems: 'center', justifyContent: 'center', padding: spacing.md}, deleteText: {color: colors.expense, fontWeight: '700', fontSize: 12}});
