import React, {useMemo, useState} from 'react';
import {Alert, FlatList, Pressable, RefreshControl, SafeAreaView, StyleSheet, Text, View} from 'react-native';
import {Plus} from 'lucide-react-native';
import {NativeStackScreenProps} from '@react-navigation/native-stack';
import {LoansStackParamList} from '../navigation/types';
import {useLoans} from '../hooks/useLoans';
import {deleteLoan} from '../services/loanService';
import {LoanDirection} from '../types/loan';
import {formatCurrency, formatShortDate} from '../utils/format';
import {Colors, controlHeight, radius, spacing} from '../constants/theme';
import {useTheme} from '../context/ThemeContext';
import AppHeader from '../components/AppHeader';

type Props = NativeStackScreenProps<LoansStackParamList, 'Loans'>;
export default function LoansScreen({navigation}: Props) {
  const {colors} = useTheme(); const styles = createStyles(colors); const {items, loading, error} = useLoans(); const [direction, setDirection] = useState<LoanDirection>('given');
  const visible = useMemo(() => items.filter(item => item.direction === direction), [direction, items]); const total = useMemo(() => visible.filter(item => item.status === 'active').reduce((sum, item) => sum + (item.outstanding ?? item.principal), 0), [visible]);
  const remove = (id: string) => Alert.alert('Delete loan?', 'This cannot be undone.', [{text: 'Cancel', style: 'cancel'}, {text: 'Delete', style: 'destructive', onPress: () => deleteLoan(id)}]);
  return <SafeAreaView style={styles.safe}><AppHeader title="Loans" /><View style={styles.actions}><Pressable accessibilityLabel="Add loan" onPress={() => navigation.navigate('AddLoan')} style={({pressed}) => [styles.add, pressed && styles.pressed]}><Plus size={20} color={colors.white} strokeWidth={2.4} /></Pressable></View><View style={styles.toggle}>{(['given', 'taken'] as LoanDirection[]).map(item => <Pressable key={item} onPress={() => setDirection(item)} style={[styles.toggleOption, direction === item && styles.selected]}><Text style={[styles.toggleText, direction === item && styles.selectedText]}>{item === 'given' ? 'Loans given' : 'Loans taken'}</Text></Pressable>)}</View><FlatList data={visible} keyExtractor={item => item.id} contentContainerStyle={styles.list} refreshControl={<RefreshControl refreshing={loading} tintColor={colors.primary} />} ListHeaderComponent={<View style={styles.summary}><Text style={styles.summaryLabel}>{direction === 'given' ? 'Given outstanding' : 'Taken outstanding'}</Text><Text style={styles.summaryValue}>{formatCurrency(total)}</Text></View>} ListEmptyComponent={!loading ? <View style={styles.empty}><Text style={styles.emptyTitle}>{error ? 'Could not load loans' : `No loans ${direction === 'given' ? 'given' : 'taken'} yet`}</Text><Text style={styles.emptyCopy}>{error ?? 'Add a loan to start tracking it.'}</Text></View> : null} renderItem={({item}) => <Pressable onPress={() => navigation.navigate('AddLoan', {loan: item})} onLongPress={() => remove(item.id)} style={({pressed}) => [styles.row, pressed && styles.rowPressed]}><View style={styles.details}><Text style={styles.name}>{item.partyName}</Text><Text style={styles.meta}>{item.status} · Started {formatShortDate(item.startedAt)}</Text></View><Text style={styles.value}>{formatCurrency(item.outstanding ?? item.principal)}</Text></Pressable>} /></SafeAreaView>;
}

const createStyles = (colors: Colors) => StyleSheet.create({safe: {flex: 1, backgroundColor: colors.canvas}, actions: {alignItems: 'flex-end', paddingHorizontal: spacing.lg, marginTop: -spacing.sm, marginBottom: spacing.sm}, add: {height: controlHeight.sm, width: controlHeight.sm, borderRadius: radius.pill, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center'}, pressed: {opacity: 0.78}, toggle: {flexDirection: 'row', marginHorizontal: spacing.lg, padding: spacing.xs, backgroundColor: colors.surfaceMuted, borderRadius: radius.md}, toggleOption: {flex: 1, minHeight: controlHeight.sm, alignItems: 'center', justifyContent: 'center', borderRadius: radius.sm}, selected: {backgroundColor: colors.surface}, toggleText: {color: colors.inkMuted, fontWeight: '700', fontSize: 12}, selectedText: {color: colors.ink}, list: {padding: spacing.lg, paddingBottom: spacing.xl * 2}, summary: {backgroundColor: colors.surface, borderRadius: radius.lg, padding: spacing.lg, marginTop: spacing.md, marginBottom: spacing.lg}, summaryLabel: {color: colors.inkMuted, fontSize: 13, fontWeight: '700'}, summaryValue: {color: colors.ink, fontSize: 24, fontWeight: '800', marginTop: spacing.xs}, row: {flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surface, borderRadius: radius.md, padding: spacing.md, marginBottom: spacing.sm}, rowPressed: {backgroundColor: colors.surfaceMuted}, details: {flex: 1}, name: {color: colors.ink, fontSize: 15, fontWeight: '800'}, meta: {color: colors.inkMuted, fontSize: 12, marginTop: spacing.xs}, value: {color: colors.ink, fontSize: 15, fontWeight: '800', marginLeft: spacing.sm}, empty: {alignItems: 'center', padding: spacing.xl, backgroundColor: colors.surface, borderRadius: radius.lg}, emptyTitle: {color: colors.ink, fontSize: 16, fontWeight: '800'}, emptyCopy: {color: colors.inkMuted, textAlign: 'center', marginTop: spacing.xs, lineHeight: 20}});
