import React from 'react';
import {Alert, Pressable, ScrollView, StyleSheet, Text, View} from 'react-native';
import {LogOut, Moon, Settings, Sun, UserRound} from 'lucide-react-native';
import {useAuth} from '../context/AuthContext';
import {ThemeMode, useTheme} from '../context/ThemeContext';
import {logout} from '../services/authService';
import AppHeader from '../components/AppHeader';
import {Colors, controlHeight, radius, spacing} from '../constants/theme';
import {SafeAreaView} from 'react-native-safe-area-context';

export default function ProfileScreen() {
  const {user} = useAuth(); const {colors, mode, setMode} = useTheme(); const styles = createStyles(colors);
  const displayName = user?.user_metadata?.display_name ?? user?.user_metadata?.full_name ?? 'Home Ledger user';
  const chooseMode = (nextMode: ThemeMode) => setMode(nextMode);
  const confirmLogout = () => Alert.alert('Log out?', 'You can sign in again anytime.', [{text: 'Cancel', style: 'cancel'}, {text: 'Log out', style: 'destructive', onPress: logout}]);
  return <SafeAreaView style={styles.flex} edges={['top']}><AppHeader eyebrow="PROFILE" title="Your profile" /><ScrollView contentContainerStyle={styles.content}><View style={styles.profileCard}><View style={styles.avatar}><UserRound size={25} color={colors.primary} strokeWidth={2.2} /></View><View style={styles.profileDetails}><Text style={styles.name}>{displayName}</Text><Text style={styles.email}>{user?.email ?? 'No email available'}</Text></View></View><Text style={styles.sectionTitle}>Theme</Text><View style={styles.themeCard}><View style={styles.settingHeading}><Settings size={18} color={colors.primary} strokeWidth={2.2} /><View><Text style={styles.settingTitle}>Appearance</Text><Text style={styles.settingCopy}>Choose how Home Ledger looks.</Text></View></View><View style={styles.themeOptions}>{(['system', 'light', 'dark'] as ThemeMode[]).map(item => <Pressable key={item} onPress={() => chooseMode(item)} style={[styles.themeOption, mode === item && styles.themeSelected]}><Text style={[styles.themeText, mode === item && styles.themeSelectedText]}>{item === 'system' ? 'System' : item === 'light' ? 'Light' : 'Dark'}</Text>{item === 'system' ? <UserRound size={16} color={mode === item ? colors.white : colors.inkMuted} /> : item === 'light' ? <Sun size={16} color={mode === item ? colors.white : colors.inkMuted} /> : <Moon size={16} color={mode === item ? colors.white : colors.inkMuted} />}</Pressable>)}</View></View><Pressable onPress={confirmLogout} style={({pressed}) => [styles.logout, pressed && styles.pressed]}><LogOut size={18} color={colors.expense} strokeWidth={2.2} /><Text style={styles.logoutText}>Log out</Text></Pressable></ScrollView></SafeAreaView>;
}

const createStyles = (colors: Colors) => StyleSheet.create({flex: {flex: 1, backgroundColor: colors.canvas}, content: {padding: spacing.lg, paddingBottom: spacing.xl * 3}, profileCard: {flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surface, borderRadius: radius.lg, padding: spacing.lg}, avatar: {height: controlHeight.md, width: controlHeight.md, borderRadius: radius.pill, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center'}, profileDetails: {flex: 1, marginLeft: spacing.md}, name: {color: colors.ink, fontSize: 17, fontWeight: '800'}, email: {color: colors.inkMuted, fontSize: 13, marginTop: spacing.xs}, sectionTitle: {color: colors.ink, fontSize: 16, fontWeight: '800', marginTop: spacing.xl, marginBottom: spacing.sm}, themeCard: {backgroundColor: colors.surface, borderRadius: radius.lg, padding: spacing.lg}, settingHeading: {flexDirection: 'row', alignItems: 'center', gap: spacing.sm}, settingTitle: {color: colors.ink, fontSize: 14, fontWeight: '800'}, settingCopy: {color: colors.inkMuted, fontSize: 12, marginTop: spacing.xs}, themeOptions: {gap: spacing.sm, marginTop: spacing.lg}, themeOption: {minHeight: controlHeight.sm, paddingHorizontal: spacing.md, borderRadius: radius.md, backgroundColor: colors.surfaceMuted, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'}, themeSelected: {backgroundColor: colors.primary}, themeText: {color: colors.inkMuted, fontSize: 13, fontWeight: '700'}, themeSelectedText: {color: colors.white}, logout: {minHeight: controlHeight.md, marginTop: spacing.xl, borderRadius: radius.md, borderWidth: 1, borderColor: colors.expense, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.xs}, logoutText: {color: colors.expense, fontSize: 14, fontWeight: '800'}, pressed: {opacity: 0.75}});
